contact_links:
  - name: WhatsApp protocol Q&A
    about: Questions on how to send specific types of messages and other protocol details which aren't directly related to pakaiwa
    url: https://github.com/pakaiwa/pakaiwa/discussions/new?category=whatsapp-protocol-q-a
